### ISSUE TITLE
Update_path append issues 

### ISSUE THREAD

**Issue by Dryja** [estatic/pydatalake-gen2#1]
Hey,
First of all thanks for creating this client. It saved me a lot of time writing similar one.

I want to report an error. 
I am using Python 3.7.2

When calling update_path function I am getting error from Requests: 
>  Value for header {Content-Length: 4} must be of type str or bytes, not <class 'int'>
That's what I do:
`client.update_path('wmfs','test/test_file','append','test')`

It is easy to figure out that change in lines 464 and 466 is needed so I changed it to:
```python
if action == "flush":
    headers["Content-Length"] = str(0)
if action == "append":
    headers["Content-Length"] = str(len(data))

```
However it does not solve the issue. After I fixed it I am getting:

> Exception: 400: {"error":{"code":"MissingRequiredQueryParameter","message":"A query parameter that's mandatory for this request is not specified.

I have compared request parameters to the datalake2 docs in order to find any mistakes but I can't find anything.

Have you tried calling `update_path` with append parameter? Was it working for you?

**Comment by estatic** [comment]
Hi @Dryja ,

Thank you for the feedback, much appreciated :)

I've made small research with your problem. Unfortunately, I didn't test update path methods at all as I'm not using it in my regular job. But, anyway, I seem found the problem with append and flush actions. So, please check the latest changes in the master branch. Once you confirm that the problem is fixed I can upload it to pypi.

The problem was with "position" variable. It's marked as optional, but in a fact, it's not :)

**Comment by Dryja** [comment]
Thank you for your quick response. 
I can confirm that both append and flush actions are working. I was able to add some chars to the file.
Thanks again for you help :)  I think I can close the issue now.

**Comment by estatic** [comment]
You are welcome! New version has been uploaded to pypi
